---
- hosts: all
  become: yes
  tasks:
    - name: Update APT package manager repositories
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Remove existing Docker packages
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc

    - name: Install Docker's official GPG key into /etc/apt/keyrings
      ansible.builtin.shell:
        cmd: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Add Docker's stable repository
      ansible.builtin.shell:
        cmd: |
          echo \
            "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
            \"$(. /etc/os-release && echo \"$VERSION_CODENAME\")\" stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update APT package manager repositories
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
...

